version = 3
final_space = true

[palette]
  base = '#24273a'
  blue = '#8aadf4'
  crust = '#181926'
  flamingo = '#f0c6c6'
  green = '#a6da95'
  lavender = '#b7bdf8'
  mantle = '#1e2030'
  maroon = '#ee99a0'
  mauve = '#c6a0f6'
  overlay0 = '#6e738d'
  overlay1 = '#8087a2'
  overlay2 = '#939ab7'
  peach = '#f5a97f'
  pink = '#f5bde6'
  red = '#ed8796'
  rosewater = '#f4dbd6'
  sapphire = '#7dc4e4'
  sky = '#91d7e3'
  subtext0 = '#a5adcb'
  subtext1 = '#b8c0e0'
  surface0 = '#363a4f'
  surface1 = '#494d64'
  surface2 = '#5b6078'
  teal = '#8bd5ca'
  text = '#cad3f5'
  yellow = '#eed49f'

[secondary_prompt]
  template = '❯ '
  foreground = 'p:mauve'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground = 'p:mauve'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'p:blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = ' {{ if .Detached }}{{ substr 0 6 .Commit.Sha }}{{ else }}{{ .Ref }}{{ end }}{{ if .Staging.Changed }}+{{ else if .Working.Changed }}*{{ end }} {{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}'
    foreground = 'p:teal'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    template = 'took {{ .FormattedMs }}'
    foreground = 'p:green'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = false
      cache_duration = 'none'
      style = 'austin'
      threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{ if ne .Code 0 }}p:red{{ end }}', '{{ if eq .Code 0 }}p:mauve{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
